### ISSUE TITLE
Support TIFF

### ISSUE THREAD

**Issue by saschanaz** [SaschaNaz/libflif.js#4]
https://github.com/image-js/tiff should be more than enough to do this.

**Comment by hrj** [comment]
@SaschaNaz I think your initial idea of supporting only the formats that the browser supports is better. Those users that need TIFF (or any other image format support) can include the respective JS decoder themselves and pass the decoded image to the FLIF encoding API.

**Comment by saschanaz** [comment]
@hrj The page is already using external decoder for APNG and GIF so I don't think TIFF should be an exception. The FLIF decoder will still always receive raw pixels for its input, which is generated by browser or external decoders.

The page is just a sample and will not make FLIF decoder code bloated.

**Comment by hrj** [comment]
Ah ok. I thought you were bundling this decoder into a library for others to use.

**Comment by saschanaz** [comment]
@mojovski TIFF support is now active. Note that decoder still only supports 8-bit output while encoder now supports 16-bit output. I will update decoder later ~~in this month~~.
